# Currently build fails due to linking errors with YAML.
clone_folder: c:\projects\gals_cuda

branches:
    only:
        - master

environment:
   matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        TOOLSET: msvc-14.1
        ADDRMD: 64
        CXXSTD: 14,17

build: off

build_script:
    - cd c:\projects\gals_cuda
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake --version
    - cmake ..
    - cmake --build . --config Release

test_script:
    - cd c:\projects\gals_cuda\build
    - ctest -C Release . --output-on-failure
