var namespaceGALS_1_1TEMPORAL__SCHEMES =
[
    [ "SEMI_LAGRANGIAN", "namespaceGALS_1_1TEMPORAL__SCHEMES_1_1SEMI__LAGRANGIAN.html", "namespaceGALS_1_1TEMPORAL__SCHEMES_1_1SEMI__LAGRANGIAN" ],
    [ "Euler", "classGALS_1_1TEMPORAL__SCHEMES_1_1Euler.html", "classGALS_1_1TEMPORAL__SCHEMES_1_1Euler" ]
];